# Generated by Django 2.1 on 2019-03-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('shoesid', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('shoesnum', models.IntegerField()),
                ('isValid', models.IntegerField(choices=[(0, '无效'), (1, '有效')], db_column='is_valid', default=1)),
            ],
        ),
        migrations.AddField(
            model_name='shoes',
            name='userid',
            field=models.ForeignKey(on_delete='CASCADE', to='shoe.User'),
        ),
    ]
